# Prints
PRINT_RACE = True
PRINT_SEASON = True
PRINT_ENGINE_CHANGES = True
PRINT_DRIVER_CHANGES = True
PRINT_RUN = True
PRINT_STATS = True
PRINT_DRIVER_UPDATES = True

# Flow
STOP_PER_RACE = False
STOP_PER_SEASON = False

# World
NUMBER_OF_SEASONS = 20
RACE_RANDOMNESS = 0.025
FORM_CHANGE = 0.1
MAX_TEAMS_PER_ENGINE = 10
DRIVERS_POOL = 40
REVOLUTION_EFFECT = 0.5
REVOLUTION_PROBABILITY = 0.2
SCOUTING_TRUE_FACTOR = 0.4

# Driver
GEN_MIN_AGE = 20
GEN_MAX_AGE = 30

# Direction
YEARLY_CHANGE = 0.1
TEAM_DEVELOPMENT_INFLUENCE = 0.1
HISTORY_YEARS = 5

# Engine
MINIMUM_RELIABILITY = 0.4
MAXIMUM_RELIABILITY = 0.95

RACE_POINTS = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1]
